Cards={
    spr_card1:{
        label:'чум',
        pict:'chum_thumb.jpg',
        audio:'chum.mp3'
    },
    spr_card2:{
        label:'медведь',
        pict:'bear_thumb.jpg',
        audio:'bear.mp3'
    },
    spr_card3:{
        label:'голубика',
        pict:'blueberry_thumb.jpg',
        audio:'blueberry.mp3'
    },
    spr_card4:{
        label:'нож',
        pict:'knife_thumb.jpg',
        audio:'knife.mp3'
    }
    
};
